# .standard.yml
plugins:
  - standard-rails

ignore:
  - 'db/schema.rb'
  - 'bin/*'
  - 'node_modules/**/*'
  - 'vendor/**/*'

TargetRubyVersion: 3.4

# Rails-specific overrides
rules:
  Rails/ApplicationRecord:
    Enabled: true
  Rails/HasManyOrHasOneDependent:
    Enabled: true
  Rails/InverseOf:
    Enabled: false # опционально для сложных связей